In [2]:
import sqlite3
import pandas as pd 
import numpy as np

In [3]:
stats = pd.read_csv("Seasons_Stats.csv")

In [7]:
stats.columns

Index(['Unnamed: 0', 'Year', 'Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP',
       'PER', 'TS%', '3PAr', 'FTr', 'ORB%', 'DRB%', 'TRB%', 'AST%', 'STL%',
       'BLK%', 'TOV%', 'USG%', 'blanl', 'OWS', 'DWS', 'WS', 'WS/48', 'blank2',
       'OBPM', 'DBPM', 'BPM', 'VORP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%',
       '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB',
       'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS'],
      dtype='object')

In [8]:
stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24691 entries, 0 to 24690
Data columns (total 53 columns):
Unnamed: 0    24691 non-null int64
Year          24624 non-null float64
Player        24624 non-null object
Pos           24624 non-null object
Age           24616 non-null float64
Tm            24624 non-null object
G             24624 non-null float64
GS            18233 non-null float64
MP            24138 non-null float64
PER           24101 non-null float64
TS%           24538 non-null float64
3PAr          18839 non-null float64
FTr           24525 non-null float64
ORB%          20792 non-null float64
DRB%          20792 non-null float64
TRB%          21571 non-null float64
AST%          22555 non-null float64
STL%          20792 non-null float64
BLK%          20792 non-null float64
TOV%          19582 non-null float64
USG%          19640 non-null float64
blanl         0 non-null float64
OWS           24585 non-null float64
DWS           24585 non-null float64
WS            24585 non-null float64
WS/48         24101 non-null float64
blank2        0 non-null float64
OBPM          20797 non-null float64
DBPM          20797 non-null float64
BPM           20797 non-null float64
VORP          20797 non-null float64
FG            24624 non-null float64
FGA           24624 non-null float64
FG%           24525 non-null float64
3P            18927 non-null float64
3PA           18927 non-null float64
3P%           15416 non-null float64
2P            24624 non-null float64
2PA           24624 non-null float64
2P%           24496 non-null float64
eFG%          24525 non-null float64
FT            24624 non-null float64
FTA           24624 non-null float64
FT%           23766 non-null float64
ORB           20797 non-null float64
DRB           20797 non-null float64
TRB           24312 non-null float64
AST           24624 non-null float64
STL           20797 non-null float64
BLK           20797 non-null float64
TOV           19645 non-null float64
PF            24624 non-null float64
PTS           24624 non-null float64
dtypes: float64(49), int64(1), object(3)
memory usage: 10.0+ MB

In [32]:
df = stats.loc[((stats['Year'] <= 2017.0) & (stats['Year'] > 1997.0 ))]

In [37]:
df.shape

(11258, 53)

In [ ]:
df['']

In [45]:
df.columns

Index(['Unnamed: 0', 'Year', 'Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP',
       'PER', 'TS%', '3PAr', 'FTr', 'ORB%', 'DRB%', 'TRB%', 'AST%', 'STL%',
       'BLK%', 'TOV%', 'USG%', 'blanl', 'OWS', 'DWS', 'WS', 'WS/48', 'blank2',
       'OBPM', 'DBPM', 'BPM', 'VORP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%',
       '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB',
       'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS'],
      dtype='object')

In [82]:
df1 =df[['Player','Pos','FG', 'FGA', 'FG%', '3P', '3PA', '3P%',
       '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB',
       'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'G']]
df1.tail()

,Player,Pos,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,G
24686,Cody Zeller,PF,253.0,443.0,0.571,0.0,1.0,0.000,253.0,442.0,...,135.0,270.0,405.0,99.0,62.0,58.0,65.0,189.0,639.0,62.0
24687,Tyler Zeller,C,78.0,158.0,0.494,0.0,1.0,0.000,78.0,157.0,...,43.0,81.0,124.0,42.0,7.0,21.0,20.0,61.0,178.0,51.0
24688,Stephen Zimmerman,C,10.0,31.0,0.323,0.0,0.0,NaN,10.0,31.0,...,11.0,24.0,35.0,4.0,2.0,5.0,3.0,17.0,23.0,19.0
24689,Paul Zipser,SF,88.0,221.0,0.398,33.0,99.0,0.333,55.0,122.0,...,15.0,110.0,125.0,36.0,15.0,16.0,40.0,78.0,240.0,44.0
24690,Ivica Zubac,C,126.0,238.0,0.529,0.0,3.0,0.000,126.0,235.0,...,41.0,118.0,159.0,30.0,14.0,33.0,30.0,66.0,284.0,38.0

In [83]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11258 entries, 13414 to 24690
Data columns (total 25 columns):
Player    11258 non-null object
Pos       11258 non-null object
FG        11258 non-null float64
FGA       11258 non-null float64
FG%       11198 non-null float64
3P        11258 non-null float64
3PA       11258 non-null float64
3P%       9282 non-null float64
2P        11258 non-null float64
2PA       11258 non-null float64
2P%       11175 non-null float64
eFG%      11198 non-null float64
FT        11258 non-null float64
FTA       11258 non-null float64
FT%       10758 non-null float64
ORB       11258 non-null float64
DRB       11258 non-null float64
TRB       11258 non-null float64
AST       11258 non-null float64
STL       11258 non-null float64
BLK       11258 non-null float64
TOV       11258 non-null float64
PF        11258 non-null float64
PTS       11258 non-null float64
G         11258 non-null float64
dtypes: float64(23), object(2)
memory usage: 2.5+ MB

In [84]:
df2 = df1.dropna()

In [85]:
df3 = df2.reset_index(drop=True)

In [86]:
df3.head()

,Player,Pos,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,G
0,Mahmoud Abdul-Rauf,PG,103.0,273.0,0.377,5.0,31.0,0.161,98.0,242.0,...,6.0,31.0,37.0,58.0,16.0,1.0,19.0,31.0,227.0,31.0
1,Tariq Abdul-Wahad,SG,144.0,357.0,0.403,4.0,19.0,0.211,140.0,338.0,...,44.0,72.0,116.0,51.0,35.0,13.0,65.0,81.0,376.0,59.0
2,Shareef Abdur-Rahim,SF,653.0,1347.0,0.485,21.0,51.0,0.412,632.0,1296.0,...,227.0,354.0,581.0,213.0,89.0,76.0,257.0,201.0,1829.0,82.0
3,Cory Alexander,PG,171.0,400.0,0.428,66.0,176.0,0.375,105.0,224.0,...,17.0,129.0,146.0,209.0,70.0,11.0,112.0,98.0,488.0,60.0
4,Cory Alexander,PG,60.0,145.0,0.414,20.0,64.0,0.313,40.0,81.0,...,7.0,40.0,47.0,71.0,25.0,5.0,47.0,53.0,165.0,37.0

In [87]:
print(df3.iloc[4]['Player'])
print(df3.iloc[3]['Player'])
df3.iloc[4]['Player'] == df3.iloc[3]['Player']

Cory Alexander
Cory Alexander

True

In [88]:
len(df3.Player.unique())

1558

In [89]:
columns = list(df3.columns)

In [97]:
df3['ORB/G'] = round(df3['ORB']/df3['G'],2)
df3['DRB/G'] = round(df3['DRB']/df3['G'],2)
df3['TRB/G'] = round(df3['TRB']/df3['G'],2)
df3['AST/G'] = round(df3['AST']/df3['G'],2)
df3['STL/G'] = round(df3['STL']/df3['G'],2)
df3['BLK/G'] = round(df3['BLK']/df3['G'],2)
df3['TOV/G'] = round(df3['TOV']/df3['G'],2)
df3['PF/G'] = round(df3['PF']/df3['G'],2)
df3['PTS/G'] = round(df3['PTS']/df3['G'],2)

In [98]:
df3.head()

,Player,Pos,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,...,G,ORB/G,DRB/G,TRB/G,AST/G,STL/G,BLK/G,TOV/G,PF/G,PTS/G
0,Mahmoud Abdul-Rauf,PG,103.0,273.0,0.377,5.0,31.0,0.161,98.0,242.0,...,31.0,0.19,1.00,1.19,1.87,0.52,0.03,0.61,1.00,7.32
1,Tariq Abdul-Wahad,SG,144.0,357.0,0.403,4.0,19.0,0.211,140.0,338.0,...,59.0,0.75,1.22,1.97,0.86,0.59,0.22,1.10,1.37,6.37
2,Shareef Abdur-Rahim,SF,653.0,1347.0,0.485,21.0,51.0,0.412,632.0,1296.0,...,82.0,2.77,4.32,7.09,2.60,1.09,0.93,3.13,2.45,22.30
3,Cory Alexander,PG,171.0,400.0,0.428,66.0,176.0,0.375,105.0,224.0,...,60.0,0.28,2.15,2.43,3.48,1.17,0.18,1.87,1.63,8.13
4,Cory Alexander,PG,60.0,145.0,0.414,20.0,64.0,0.313,40.0,81.0,...,37.0,0.19,1.08,1.27,1.92,0.68,0.14,1.27,1.43,4.46

In [99]:
df3.columns

Index(['Player', 'Pos', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', '2P', '2PA',
       '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL',
       'BLK', 'TOV', 'PF', 'PTS', 'G', 'ORB/G', 'DRB/G', 'TRB/G', 'AST/G',
       'STL/G', 'BLK/G', 'TOV/G', 'PF/G', 'PTS/G'],
      dtype='object')

In [101]:
df4 = df3[['Player', 'Pos', 'FG%', '3P%','2P%', 'FT%','ORB/G', 'DRB/G', 'TRB/G', 'AST/G',
       'STL/G', 'BLK/G', 'TOV/G', 'PF/G', 'PTS/G']]

In [102]:
df4.tail()

,Player,Pos,FG%,3P%,2P%,FT%,ORB/G,DRB/G,TRB/G,AST/G,STL/G,BLK/G,TOV/G,PF/G,PTS/G
9044,Thaddeus Young,PF,0.527,0.381,0.557,0.523,1.77,4.30,6.07,1.65,1.54,0.41,1.30,1.82,11.00
9045,Cody Zeller,PF,0.571,0.000,0.572,0.679,2.18,4.35,6.53,1.60,1.00,0.94,1.05,3.05,10.31
9046,Tyler Zeller,C,0.494,0.000,0.497,0.564,0.84,1.59,2.43,0.82,0.14,0.41,0.39,1.20,3.49
9047,Paul Zipser,SF,0.398,0.333,0.451,0.775,0.34,2.50,2.84,0.82,0.34,0.36,0.91,1.77,5.45
9048,Ivica Zubac,C,0.529,0.000,0.536,0.653,1.08,3.11,4.18,0.79,0.37,0.87,0.79,1.74,7.47

In [107]:
len(df4.Player.unique())

1558

In [143]:
df5 = df4.groupby('Player')

In [144]:
df5.head()

,Player,Pos,FG%,3P%,2P%,FT%,ORB/G,DRB/G,TRB/G,AST/G,STL/G,BLK/G,TOV/G,PF/G,PTS/G
0,Mahmoud Abdul-Rauf,PG,0.377,0.161,0.405,1.000,0.19,1.00,1.19,1.87,0.52,0.03,0.61,1.00,7.32
1,Tariq Abdul-Wahad,SG,0.403,0.211,0.414,0.672,0.75,1.22,1.97,0.86,0.59,0.22,1.10,1.37,6.37
2,Shareef Abdur-Rahim,SF,0.485,0.412,0.488,0.784,2.77,4.32,7.09,2.60,1.09,0.93,3.13,2.45,22.30
3,Cory Alexander,PG,0.428,0.375,0.469,0.784,0.28,2.15,2.43,3.48,1.17,0.18,1.87,1.63,8.13
4,Cory Alexander,PG,0.414,0.313,0.494,0.676,0.19,1.08,1.27,1.92,0.68,0.14,1.27,1.43,4.46
5,Cory Alexander,PG,0.435,0.411,0.455,0.846,0.43,3.87,4.30,6.00,1.96,0.26,2.83,1.96,14.04
6,Ray Allen,SG,0.428,0.364,0.453,0.875,1.55,3.39,4.94,4.34,1.35,0.15,3.21,2.98,19.54
7,Derek Anderson,SF,0.408,0.202,0.442,0.873,0.83,2.00,2.83,3.44,1.30,0.20,1.94,2.06,11.67
8,Greg Anderson,C,0.444,0.000,0.474,0.390,0.78,1.58,2.36,0.30,0.38,0.20,0.34,1.70,1.76
9,Kenny Anderson,PG,0.398,0.356,0.411,0.789,0.64,2.20,2.84,5.66,1.43,0.02,2.34,2.21,12.23
10,Kenny Anderson,PG,0.387,0.353,0.398,0.772,0.80,2.18,2.98,5.44,1.36,0.02,2.53,2.20,12.60
11,Kenny Anderson,PG,0.435,0.370,0.450,0.837,0.19,2.25,2.44,6.25,1.62,0.00,1.81,2.25,11.19
12,Nick Anderson,SF,0.455,0.360,0.493,0.638,1.69,3.43,5.12,2.05,1.24,0.40,1.47,1.69,15.34
13,Shandon Anderson,SG,0.538,0.219,0.560,0.735,1.05,1.72,2.77,1.09,0.80,0.22,1.11,1.77,8.30
14,Chris Anstey,C,0.398,0.188,0.414,0.716,1.29,2.54,3.83,0.85,0.76,0.66,1.00,2.32,5.85
15,Greg Anthony,PG,0.430,0.415,0.442,0.663,0.22,1.16,1.39,2.56,0.80,0.04,1.14,1.21,5.24
16,B.J. Armstrong,PG,0.493,0.257,0.539,0.840,0.24,0.91,1.15,2.27,0.44,0.00,0.64,1.12,3.95
17,B.J. Armstrong,PG,0.316,0.000,0.333,0.714,1.00,0.75,1.75,1.50,1.00,0.00,1.75,1.50,4.25
18,B.J. Armstrong,PG,0.510,0.265,0.563,0.860,0.19,0.92,1.11,2.32,0.40,0.00,0.56,1.10,3.94
19,Darrell Armstrong,PG,0.411,0.368,0.420,0.854,1.35,1.96,3.31,4.92,1.21,0.10,2.33,2.00,9.21
20,Vincent Askew,SG,0.352,0.000,0.365,0.718,0.70,1.57,2.27,1.27,0.63,0.17,1.17,1.30,2.20
21,Keith Askins,SF,0.320,0.284,0.375,0.632,0.61,1.59,2.20,0.63,0.59,0.26,0.57,2.33,2.41
22,Stacey Augmon,SG,0.414,0.143,0.419,0.603,1.46,1.85,3.31,1.24,0.80,0.45,1.14,2.03,5.68
23,Isaac Austin,C,0.466,0.000,0.470,0.669,2.55,4.59,7.14,2.24,0.78,0.72,2.64,2.96,13.53
24,Isaac Austin,C,0.474,0.000,0.476,0.680,2.29,4.06,6.35,1.67,0.83,0.65,2.25,3.12,12.67
25,Isaac Austin,C,0.454,0.000,0.461,0.652,3.08,5.65,8.73,3.38,0.69,0.85,3.42,2.65,15.23
26,Vin Baker,C,0.542,0.143,0.545,0.591,3.49,4.51,8.00,1.85,1.11,1.05,2.12,3.39,19.20
27,Charles Barkley*,PF,0.485,0.214,0.520,0.746,3.54,8.13,11.68,3.19,1.04,0.41,2.16,2.75,15.24
28,Dana Barros,PG,0.461,0.407,0.499,0.847,0.35,1.56,1.91,3.58,1.04,0.08,1.34,1.55,9.80
29,Brent Barry,SG,0.421,0.393,0.444,0.858,0.50,2.45,2.95,2.64,1.10,0.47,1.79,2.03,10.88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8995,Jonas Valanciunas,C,0.557,0.500,0.557,0.811,2.82,6.66,9.49,0.71,0.46,0.79,1.32,2.70,11.99
8996,Denzel Valentine,SG,0.354,0.351,0.363,0.778,0.19,2.46,2.65,1.11,0.53,0.12,0.86,1.51,5.11
8997,Fred VanVleet,PG,0.351,0.379,0.341,0.818,0.11,1.03,1.14,0.95,0.46,0.05,0.41,0.97,2.89
8999,Rashad Vaughn,SG,0.365,0.321,0.413,0.400,0.10,1.10,1.20,0.56,0.46,0.24,0.34,0.78,3.46
9000,Noah Vonleh,PF,0.481,0.350,0.492,0.638,1.77,3.46,5.23,0.42,0.41,0.36,0.86,2.08,4.42
9001,Nikola Vucevic,C,0.468,0.307,0.481,0.669,2.35,8.04,10.39,2.77,1.03,0.99,1.56,2.40,14.61
9007,Taurean Waller-Prince,SF,0.400,0.324,0.443,0.787,0.42,2.24,2.66,0.93,0.73,0.46,1.03,1.63,5.68
9008,T.J. Warren,SF,0.495,0.265,0.527,0.773,1.89,3.24,5.14,1.14,1.15,0.59,0.86,2.65,14.41
9010,Briante Weber,PG,0.417,0.100,0.480,0.688,0.40,0.90,1.30,1.05,0.60,0.05,0.40,0.80,3.10
9011,Briante Weber,PG,0.357,0.000,0.455,0.667,0.00,0.57,0.57,0.71,0.43,0.14,0.43,0.57,1.71
9012,Briante Weber,PG,0.435,0.143,0.487,0.692,0.62,1.08,1.69,1.23,0.69,0.00,0.38,0.92,3.85
9015,Okaro White,PF,0.379,0.353,0.396,0.909,0.71,1.63,2.34,0.60,0.29,0.29,0.51,1.49,2.80
9016,Isaiah Whitehead,PG,0.402,0.295,0.446,0.805,0.44,2.08,2.52,2.63,0.58,0.49,1.95,2.40,7.44
9017,Andrew Wiggins,SF,0.452,0.356,0.473,0.760,1.26,2.76,4.01,2.30,1.00,0.37,2.28,2.23,23.57
9018,C.J. Wilcox,SG,0.258,0.200,0.313,1.000,0.18,0.36,0.55,0.55,0.09,0.05,0.27,0.36,0.95
9019,Alan Williams,C,0.517,0.000,0.519,0.625,2.00,4.21,6.21,0.49,0.57,0.68,0.79,2.66,7.36
9031,Troy Williams,SF,0.437,0.290,0.524,0.656,0.50,1.80,2.30,0.83,0.90,0.33,1.10,2.00,6.17
9032,Troy Williams,SF,0.415,0.244,0.500,0.600,0.25,1.62,1.88,0.79,1.00,0.38,1.12,1.75,5.29
9033,Troy Williams,SF,0.500,0.381,0.609,0.857,1.50,2.50,4.00,1.00,0.50,0.17,1.00,3.00,9.67
9034,Kyle Wiltjer,PF,0.286,0.308,0.000,0.500,0.29,0.43,0.71,0.14,0.21,0.07,0.36,0.29,0.93
9035,Justise Winslow,SF,0.356,0.200,0.384,0.617,1.28,3.94,5.22,3.67,1.50,0.33,1.83,2.89,10.89
9036,Jeff Withey,C,0.534,0.000,0.539,0.750,1.02,1.35,2.37,0.14,0.31,0.63,0.27,1.02,2.86
9037,Christian Wood,PF,0.522,0.000,0.667,0.733,1.08,1.15,2.23,0.15,0.23,0.46,0.54,0.85,2.69
9040,Delon Wright,PG,0.422,0.333,0.453,0.764,0.59,1.19,1.78,2.11,1.00,0.41,0.93,1.15,5.56
9041,James Young,SG,0.431,0.343,0.565,0.667,0.21,0.69,0.90,0.14,0.34,0.07,0.14,0.52,2.34
9042,Joe Young,PG,0.361,0.217,0.429,0.733,0.03,0.48,0.52,0.45,0.12,0.00,0.15,0.15,2.06
9045,Cody Zeller,PF,0.571,0.000,0.572,0.679,2.18,4.35,6.53,1.60,1.00,0.94,1.05,3.05,10.31
9046,Tyler Zeller,C,0.494,0.000,0.497,0.564,0.84,1.59,2.43,0.82,0.14,0.41,0.39,1.20,3.49
9047,Paul Zipser,SF,0.398,0.333,0.451,0.775,0.34,2.50,2.84,0.82,0.34,0.36,0.91,1.77,5.45
9048,Ivica Zubac,C,0.529,0.000,0.536,0.653,1.08,3.11,4.18,0.79,0.37,0.87,0.79,1.74,7.47

In [188]:
df6 = df4.groupby('Player')[['FG%', '3P%','2P%', 'FT%','ORB/G', 'DRB/G', 'TRB/G', 'AST/G',
       'STL/G', 'BLK/G', 'TOV/G', 'PF/G', 'PTS/G']].mean()

In [189]:
df7 = df6.round(3)

In [190]:
df7.tail()

,FG%,3P%,2P%,FT%,ORB/G,DRB/G,TRB/G,AST/G,STL/G,BLK/G,TOV/G,PF/G,PTS/G
Player,,,,,,,,,,,,,
Zarko Cabarkapa,0.441,0.290,0.473,0.750,0.728,1.540,2.268,0.612,0.232,0.160,0.808,1.507,4.885
Zaza Pachulia,0.468,0.000,0.472,0.752,2.389,3.814,6.203,1.445,0.765,0.359,1.480,2.622,7.477
Zoran Dragic,0.342,0.182,0.543,0.589,0.313,0.187,0.500,0.293,0.107,0.000,0.270,0.350,1.650
Zoran Planinic,0.407,0.296,0.447,0.676,0.327,1.023,1.347,1.120,0.403,0.043,0.817,1.607,3.860
Zydrunas Ilgauskas,0.476,0.140,0.478,0.774,2.839,4.377,7.218,1.101,0.493,1.545,1.798,3.258,12.745

In [191]:
df7['POS'] = df5['Pos'].unique()

In [192]:
df7.tail()

,FG%,3P%,2P%,FT%,ORB/G,DRB/G,TRB/G,AST/G,STL/G,BLK/G,TOV/G,PF/G,PTS/G,POS
Player,,,,,,,,,,,,,,
Zarko Cabarkapa,0.441,0.290,0.473,0.750,0.728,1.540,2.268,0.612,0.232,0.160,0.808,1.507,4.885,[PF]
Zaza Pachulia,0.468,0.000,0.472,0.752,2.389,3.814,6.203,1.445,0.765,0.359,1.480,2.622,7.477,[C]
Zoran Dragic,0.342,0.182,0.543,0.589,0.313,0.187,0.500,0.293,0.107,0.000,0.270,0.350,1.650,[SG]
Zoran Planinic,0.407,0.296,0.447,0.676,0.327,1.023,1.347,1.120,0.403,0.043,0.817,1.607,3.860,"[SG, PG]"
Zydrunas Ilgauskas,0.476,0.140,0.478,0.774,2.839,4.377,7.218,1.101,0.493,1.545,1.798,3.258,12.745,[C]

In [193]:
df8 = df7

In [196]:
df8['POS'] = df8['POS'].map(lambda x: x[0])

In [197]:
df8.POS

Player
A.C. Green                PF
A.J. Guyton               PG
A.J. Hammons               C
A.J. Price                PG
Aaron Brooks              PG
Aaron Gordon              PF
Aaron Gray                 C
Aaron Harrison            SG
Aaron McKie            SG-SF
Aaron Williams            PF
Acie Law                  PG
Adam Harrington           SG
Adam Keefe                PF
Adam Morrison             PF
Adonal Foyle               C
Adonis Jordan             PG
Adonis Thomas             SF
Adreian Payne             PF
Adrian Griffin            SG
Al Harrington             PF
Al Horford                 C
Al Jefferson              PF
Al Thornton               PF
Al-Farouq Aminu           SF
Alan Anderson             SF
Alan Henderson            PF
Alan Williams              C
Alando Tucker             SF
Alec Burks                SG
Alex Abrines              SG
                       ...
Will Cherry               PG
Will Conroy               PG
Will Perdue                C
Will Solomon              SG
William Avery             PG
Willie Burton             SF
Willie Cauley-Stein        C
Willie Green              SG
Willie Reed                C
Willie Warren             PG
Willy Hernangomez          C
Wilson Chandler           SF
Xavier Henry              SG
Xavier Munford            SG
Xavier Silas              SG
Yakhouba Diawara          SG
Yao Ming*                  C
Yaroslav Korolev          SF
Yi Jianlian               PF
Yogi Ferrell              PG
Yuta Tabuse               PG
Zabian Dowdell            PG
Zach LaVine               PG
Zach Randolph             PF
Zan Tabak                  C
Zarko Cabarkapa           PF
Zaza Pachulia              C
Zoran Dragic              SG
Zoran Planinic            SG
Zydrunas Ilgauskas         C
Name: POS, Length: 1558, dtype: object

In [199]:
df8.head()

,FG%,3P%,2P%,FT%,ORB/G,DRB/G,TRB/G,AST/G,STL/G,BLK/G,TOV/G,PF/G,PTS/G,POS
Player,,,,,,,,,,,,,,
A.C. Green,0.442,0.062,0.448,0.675,1.890,3.722,5.615,0.865,0.633,0.202,0.602,1.572,5.440,PF
A.J. Guyton,0.384,0.382,0.381,0.824,0.285,0.750,1.035,1.870,0.245,0.155,0.775,0.785,5.710,PG
A.J. Hammons,0.405,0.500,0.375,0.450,0.360,1.270,1.640,0.180,0.050,0.590,0.450,0.950,2.180,C
A.J. Price,0.373,0.273,0.447,0.632,0.251,1.093,1.344,1.971,0.401,0.021,0.753,0.735,5.578,PG
Aaron Brooks,0.410,0.359,0.444,0.838,0.403,1.268,1.671,3.174,0.591,0.134,1.582,1.932,9.604,PG

In [221]:
players = pd.read_csv("Sez/Players.csv.xls")
players.head()
type(players)

pandas.core.frame.DataFrame

In [222]:
players.columns

Index(['Unnamed: 0', 'Player', 'height', 'weight', 'collage', 'born',
       'birth_city', 'birth_state'],
      dtype='object')

In [224]:
players1 = players.drop('Unnamed: 0', axis=1)

players1.head()

,Player,height,weight,collage,born,birth_city,birth_state
0,Curly Armstrong,180.0,77.0,Indiana University,1918.0,NaN,NaN
1,Cliff Barker,188.0,83.0,University of Kentucky,1921.0,Yorktown,Indiana
2,Leo Barnhorst,193.0,86.0,University of Notre Dame,1924.0,NaN,NaN
3,Ed Bartels,196.0,88.0,North Carolina State University,1925.0,NaN,NaN
4,Ralph Beard,178.0,79.0,University of Kentucky,1927.0,Hardinsburg,Kentucky

In [228]:
players2 = players1.drop(['collage', 'born', 'birth_city', 'birth_state'], axis=1)

In [232]:
final_df = pd.merge(df8,players2, on='Player', how='left')

In [233]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1558 entries, 0 to 1557
Data columns (total 17 columns):
Player    1558 non-null object
FG%       1558 non-null float64
3P%       1558 non-null float64
2P%       1558 non-null float64
FT%       1558 non-null float64
ORB/G     1558 non-null float64
DRB/G     1558 non-null float64
TRB/G     1558 non-null float64
AST/G     1558 non-null float64
STL/G     1558 non-null float64
BLK/G     1558 non-null float64
TOV/G     1558 non-null float64
PF/G      1558 non-null float64
PTS/G     1558 non-null float64
POS       1558 non-null object
height    1558 non-null float64
weight    1558 non-null float64
dtypes: float64(15), object(2)
memory usage: 219.1+ KB